# Generated by Django 5.2.6 on 2025-10-31 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Sid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User')),
            ],
        ),
    ]
